name: "Npm Release"
description: "This action will update version, publish release and push to npm registry"
inputs:
  version_increment:
    description: 'The version increment (major, minor, patch)'
    required: true
    default: 'patch'

  repository:
    description: 'Repository to the project'
    required: true

  github_token:
    description: 'Github token to the project'
    required: true

runs:
  using: "composite"
  steps:    
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        repository: ${{ inputs.repository }}

    - name: Set up Git
      shell: bash
      run: |
        git config user.email "github@action.com"
        git config user.name "Github Action"
        echo ${{ inputs.github_token }} > token.txt
        git config credential.helper "store --file=token.txt"

    - name: Update version
      shell: bash
      run: |
        echo NEW_VERSION=$(yarn version --${{ inputs.version_increment }} --json | jq -r '.data | select(contains("New version")) | split(":")[1] | gsub(" ";"")') >> $GITHUB_ENV
        git push --follow-tags
      env:
        REF: ${{ github.ref }}

    - name: Set up .npmrc
      uses: actions/setup-node@v3
      with:
        always-auth: true
        node-version: '16.x'
        registry-url: 'https://npm.pkg.github.com'
        # Defaults to the user or organization that owns the workflow file
        scope: '@RICHARD-Quentin'
        
    - name: Echo .npmrc
      shell: bash
      run: echo ~/.npmrc
        
    - name: Run npm install
      shell: bash
      run: npm install
      
    - name: Run build
      shell: bash
      run: npm run build
      
#     - name: Set up NPM token
#       shell: bash
#       run: echo "//npm.pkg.github.com/:_authToken=${{ inputs.github_token }}" > ~/.npmrc

    
    - name: Publish
      shell: bash
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ inputs.github_token }}
